/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as GeneratedPostsRouteImport } from './routes/generated-posts'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BrandSettingsRouteImport } from './routes/brand-settings'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiGeneratorRouteImport } from './routes/ai-generator'
import { Route as IndexRouteImport } from './routes/index'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratedPostsRoute = GeneratedPostsRouteImport.update({
  id: '/generated-posts',
  path: '/generated-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSettingsRoute = BrandSettingsRouteImport.update({
  id: '/brand-settings',
  path: '/brand-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGeneratorRoute = AiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand-settings': typeof BrandSettingsRoute
  '/campaigns': typeof CampaignsRoute
  '/events': typeof EventsRoute
  '/generated-posts': typeof GeneratedPostsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand-settings': typeof BrandSettingsRoute
  '/campaigns': typeof CampaignsRoute
  '/events': typeof EventsRoute
  '/generated-posts': typeof GeneratedPostsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand-settings': typeof BrandSettingsRoute
  '/campaigns': typeof CampaignsRoute
  '/events': typeof EventsRoute
  '/generated-posts': typeof GeneratedPostsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-generator'
    | '/analytics'
    | '/assets'
    | '/brand-settings'
    | '/campaigns'
    | '/events'
    | '/generated-posts'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-generator'
    | '/analytics'
    | '/assets'
    | '/brand-settings'
    | '/campaigns'
    | '/events'
    | '/generated-posts'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/ai-generator'
    | '/analytics'
    | '/assets'
    | '/brand-settings'
    | '/campaigns'
    | '/events'
    | '/generated-posts'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiGeneratorRoute: typeof AiGeneratorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  BrandSettingsRoute: typeof BrandSettingsRoute
  CampaignsRoute: typeof CampaignsRoute
  EventsRoute: typeof EventsRoute
  GeneratedPostsRoute: typeof GeneratedPostsRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generated-posts': {
      id: '/generated-posts'
      path: '/generated-posts'
      fullPath: '/generated-posts'
      preLoaderRoute: typeof GeneratedPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-settings': {
      id: '/brand-settings'
      path: '/brand-settings'
      fullPath: '/brand-settings'
      preLoaderRoute: typeof BrandSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-generator': {
      id: '/ai-generator'
      path: '/ai-generator'
      fullPath: '/ai-generator'
      preLoaderRoute: typeof AiGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGeneratorRoute: AiGeneratorRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  BrandSettingsRoute: BrandSettingsRoute,
  CampaignsRoute: CampaignsRoute,
  EventsRoute: EventsRoute,
  GeneratedPostsRoute: GeneratedPostsRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
